//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doancs
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string MaHopDong { get; set; }
        public string MaPhong { get; set; }
        public string MaNguoiThue { get; set; }
        public Nullable<System.DateTime> NgayBatDauThue { get; set; }
        public Nullable<System.DateTime> NgayKetThucThue { get; set; }
    
        public virtual NguoiThueTro NguoiThueTro { get; set; }
        public virtual PhongTro PhongTro { get; set; }
    }
}
