//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doancs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYTRO_LINQ_Entities : DbContext
    {
        public QUANLYTRO_LINQ_Entities()
            : base("name=QUANLYTRO_LINQ_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CoSoVatChat> CoSoVatChat { get; set; }
        public virtual DbSet<HoaDon> HoaDon { get; set; }
        public virtual DbSet<HopDong> HopDong { get; set; }
        public virtual DbSet<nguoidung> nguoidung { get; set; }
        public virtual DbSet<NguoiThueTro> NguoiThueTro { get; set; }
        public virtual DbSet<PhongTro> PhongTro { get; set; }
        public virtual DbSet<SoDienNuoc> SoDienNuoc { get; set; }
    }
}
