//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doancs
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoDienNuoc
    {
        public string MaPhong { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<int> ChiSoDienCu { get; set; }
        public Nullable<int> ChiSoDienMoi { get; set; }
        public Nullable<int> ChiSoNuocCu { get; set; }
        public Nullable<int> ChiSoNuocMoi { get; set; }
    
        public virtual PhongTro PhongTro { get; set; }
    }
}
